services:
  backend:
    build: ./backend
    expose:
      - 5000
    restart: always
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 --threads 5 manage:app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      DATABASE: postgres
      DATABASE_URI: postgresql://admin:admin@db:5432
    deploy:
      mode: Replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - josa
    volumes:
      - ./backend/src/uploads:/app/src/uploads
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend-cont
    restart: always
    ports:
      - "80:80"
    networks:
      - josa
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    networks:
      - josa
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  worker:
    build: ./backend
    command: ./celery.sh
    env_file:
      - ./backend/.env.prod
    depends_on:
      - backend
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - josa
    volumes:
      - ./backend/src/uploads:/app/src/uploads

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - josa

volumes:
  postgres_data: {}

networks:
  josa:
    driver: bridge
